<div class="container">
    <div class="row">


        <div class="col-md-8 col-md-offset-2">

            <h2>Business hours </h2>
            <hr class="colorgraph">

            <table id="business-hours">
                <tr>
                    <th>Sunday</th>
                    <td>Closed</td>
                </tr>
                <tr>
                    <th>Monday</th>
                    <td>9am - 5pm</td>
                </tr>
                <tr>
                    <th>Tuesday</th>
                    <td>9am - 5pm</td>
                </tr>
                <tr>
                    <th>Wednesday</th>
                    <td>9am - 5pm</td>
                </tr>
                <tr>
                    <th>Thursday</th>
                    <td>9am - 5pm</td>
                </tr>
                <tr>
                    <th>Friday</th>
                    <td>9am - 5pm</td>
                </tr>
                <tr>
                    <th>Saturday</th>
                    <td>10am - 2pm</td>
                </tr>
            </table>


            <h2>Contact us
                <small>get it touch using the form below, and we will get back to you shortly.</small>
            </h2>
            <hr class="colorgraph">
            <div id="sendmessage">Your message has been sent. Thank you!</div>
            <div id="errormessage"></div>
            <form id="contact-form" role="form" class="contactForm">
                <div class="form-group">
                    <input type="text" name="name" class="form-control" id="name" placeholder="Your Name"
                           data-rule="minlen:4" data-msg="Please enter at least 4 chars">
                    <div class="error"></div>
                </div>
                <div class="form-group">
                    <input type="email" class="form-control" name="email" id="email" placeholder="Your Email"
                           data-rule="email" data-msg="Please enter a valid email">
                    <div class="error"></div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject"
                           data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject">
                    <div class="error"></div>
                </div>
                <div class="form-group">
                    <textarea class="form-control" name="message" rows="5" data-rule="required"
                              data-msg="Please write something for us" placeholder="Message"></textarea>
                    <div class="error"></div>
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-theme btn-block btn-md">Send Message</button>
                </div>
            </form>


        </div>
    </div>


    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Map view</h2>
            <hr class="colorgraph">

            <section id="content">

                <div class="map">
                    <div id="google-map" data-latitude="51.478657" data-longitude="-0.064545"></div>
                </div>
            </section>
            <hr class="colorgraph">
        </div>
    </div>

</div>

