<article>

    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2">

                <form role="form" name="property" id="property-form" class="register-form">
                    <?php if (isset($property['id'])) : ?>
                        <h2>Edit property</h2>
                    <?php else : ?>
                        <h2>Create property</h2>
                    <?php endif; ?>

                    <hr class="colorgraph">
                    <div id="sendmessage">Property has been successfully created. </div>
                    <div id="errormessage"></div>

                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" name="title" class="form-control input-lg"
                               value="<?= $property['title'] ?>" placeholder="Title" tabindex="4">

                        <div class="error"></div>
                    </div>

                    <div class="form-group">
                        <label>Description</label>
                        <textarea name="description" class="form-control input-lg"
                                  placeholder="Description" tabindex="3"><?= $property['description'] ?></textarea>
                        <div class="error"></div>
                    </div>

                    <div class="form-group">
                        <label for="sel1">Rent or Buy</label>
                        <select name="rentalProperty" class="form-control" id="rentalProperty">
                            <option value="" selected>Please select</option>
                            <option value="buy" <?=!$property['rentalProperty'] ? 'selected' : ''?> > Buy </option>
                            <option value="rent" <?=$property['rentalProperty'] ? 'selected' : ''?>>Rent</option>
                        </select>
                        <div class="error"></div>
                    </div>

                    <div class="form-group">
                        <label for="sel1">Property Status</label>
                        <select name="status" class="form-control" id="status">
                            <?php  LayoutControl::showSelectControl($dropDowns['status'], $property['status']) ?>
                        </select>
                        <div class="error"></div>
                    </div>

                    <div class="form-group">
                        <label for="propertyType">Type of property</label>

                        <select name="propertyType" class="form-control" id="propertyType">
                            <?php  LayoutControl::showSelectControl($dropDowns['propertyType'], $property['propertyType']) ?>
                        </select>
                        <div class="error"></div>
                    </div>

                    <div class="form-group">
                        <label>Price</label>
                        <input type="text" name="price" class="form-control" placeholder="Property's price" value="<?= $property['price'] ?>">
                        <div class="error"></div>
                    </div>

                    <div class="form-group">
                        <label for="noOfBedrooms">No. of bedrooms</label>
                        <select id="noOfBedrooms" class="form-control" name="noOfBedrooms">
                            <?php  LayoutControl::showSelectControl($dropDowns['noOfBedrooms'], $property['noOfBedrooms']) ?>
                        </select>
                        <div class="error"></div>
                    </div>

                    <div class="form-group">
                        <label for="area">Area</label>
                        <select id="area" class="form-control" name="area">
                            <?php  LayoutControl::showSelectControl($dropDowns['areas'], $property['area']) ?>
                        </select>
                        <div class="error"></div>
                    </div>

                    <div class="form-group">
                        <label>Postcode</label>
                        <input type="text" name="postcode" class="form-control" id="name" placeholder="Property's postcode" value="<?= $property['postcode'] ?>">
                        <div class="error"></div>
                    </div>

                    <div class="form-group">
                        <label>Images</label>

                        <div class="dropzone clsbox" id="mydropzone" data-images="<?=$property['images'];?>">
                        </div>

                        <div class="error"></div>
                    </div>

                    <input name="id" type="hidden" value="<?= isset($property['id']) ? $property['id'] : null; ?>">
                    <input name="images" type="hidden" value="<?= isset($property['images']) ? $property['images'] : null; ?>">


                    <hr class="colorgraph">
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <input type="submit" value="Save" class="btn btn-theme btn-block btn-lg" tabindex="7">
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <div class="btn btn-warning btn-block btn-lg" id="cancel-button"> Cancel</div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</article>