<section class="callaction">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="cta-text">
                    <h2>Welcome to <span>Relocate Right</span> website.</h2>
                    <p>
                        We have been helping people to rent and buy properties in the London area
                        for over ten years and would love to help you do the same.
                        Let us know what are you looking for below and then browse the properties we have available.
                        If you have a property to sell or rent click <a>here</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>