<article>
    <div class="row">
        <?php if(!empty($_GET['message'])) : ?>
            <div id="sendmessage" class="fade-out"><?=$_GET['message']?></div>
        <?php endif; ?>

        <div class="col-sm-6">
            <div class="post-image">
                <div class="post-heading">
                    <h3><a><?= $property['title']; ?>t</a></h3>
                </div>


                <div class="sp-wrap">

                    <?php
                    $images = explode(',', $property['images']);
                    foreach ($images as $image):
                        ?>
                        <a href="server/uploads/<?=$image?>"><img src="server/uploads/<?=$image?>" alt=""></a>
                    <?php endforeach;?>

                </div>

            </div>

            <div style="clear:both"></div>

            <div>
                <label>Property Type:</label>
                <?= PropertyManager::getDropDownValueLabel('propertyType', $property['propertyType']); ?>
            </div>

            <div>
                <label>Status:</label>
                <?= PropertyManager::getDropDownValueLabel('status', $property['status']); ?>
            </div>

            <div>
                <label>Area:</label>
                <?= PropertyManager::getDropDownValueLabel('areas', $property['area']); ?>
            </div>

            <div>
                <label>Number of rooms:</label>
                <?= PropertyManager::getDropDownValueLabel('noOfBedrooms', $property['noOfBedrooms']); ?>
            </div>

            <div>
                <label>Price:</label>
                <?= "(£)" . $property['price'] ?>
            </div>
            <div>
                <label>Published:</label>
                <?= date('d/m/Y', strtotime($property['created_at'])); ?>
            </div>


            <p>
                <?= $property['description']; ?>
            </p>
            <?php if (Authorization::hasAdminAccess()) : ?>
                <a class="btn btn-primary" href="/property/edit/<?=$property['id'];?>">Edit</a>
                <a class="btn btn-primary" href="/property/delete/<?=$property['id'];?>" >Delete</a>
            <?php endif; ?>

        </div>
        <div class="col-sm-6">
            <div id="map" data-lat="<?= $property['lat']; ?>" data-lng="<?= $property['lng']; ?>"></div>
        </div>
    </div>
</article>

