<article>
    <div class="row">
        <div class="col-sm-6">
            <div class="post-image">
                <div class="post-heading">
                    <h3><a><?= $property['title']; ?>t</a></h3>
                </div>
                <img src="client/assets/img/1.jpg" alt="" class="img-responsive">
            </div>

            <div>
                <label>Property Type:</label>
                <?= PropertyManager::getDropDownValueLabel('propertyType', $property['propertyType']); ?>
            </div>

            <div>
                <label>Status:</label>
                <?= PropertyManager::getDropDownValueLabel('status', $property['status']); ?>
            </div>

            <div>
                <label>Area:</label>
                <?= PropertyManager::getDropDownValueLabel('areas', $property['area']); ?>
            </div>

            <div>
                <label>Number of rooms:</label>
                <?= PropertyManager::getDropDownValueLabel('noOfBedrooms', $property['noOfBedrooms']); ?>
            </div>

            <div>
                <label>Price:</label>
                <?= "(£)" . $property['price'] ?>
            </div>
            <div>
                <label>Published:</label>
                <?= $property['created_at'] ?>
            </div>


            <p>
                <?= $property['description']; ?>
            </p>
            <?php if (Authorization::hasAdminAccess()) : ?>
            <button class="btn btn-primary" data-property-id="<?=$property['id'];?>" id="edit-property-button">Edit</button>
            <?php endif; ?>

        </div>
        <div class="col-sm-6">
            <div id="map" data-lat="<?= $property['lat']; ?>" data-lng="<?= $property['lng']; ?>"></div>
        </div>
    </div>
</article>

