<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>You want to sell or rent out your property?</h2>
            <p>
                Please provide the few details of your property in the form below, and one of our team
                will be in touch shortly to create a professional profile for your property and make it available
                to the thousands of people looking for their perfect place to live.
            </p>

            <hr class="colorgraph">
            <div id="sendmessage">Your message has been sent. Thank you!</div>
            <div id="errormessage"></div>
            <form role="form" class="selling-form" id="selling-form">

                <div class="form-group">
                    <label >Buy or sell</label>
                    <select name="requestType" class="form-control" id="sel1">
                        <option value="" selected>Please select</option>
                        <option value="sell">Sell</option>
                        <option value="rent">Rent</option>
                    </select>
                    <div class="error"></div>
                </div>

                <div class="form-group">
                    <label for="propertyType">Type of property</label>

                    <select name="propertyType" class="form-control" id="propertyType">
                        <option value="" selected>Please select</option>
                        <option value="houses">Houses</option>
                        <option value="flats">Flats / Apartments</option>
                        <option value="bungalows">Bungalows</option>
                        <option value="commercial">Commercial Property</option>
                        <option value="other">Other</option>
                    </select>
                    <div class="error"></div>
                </div>

                <div class="form-group">
                    <label for="noOfBedrooms">No. of bedrooms</label>

                    <select id="noOfBedrooms" class="form-control" name="noOfBedrooms">
                        <option value="" selected="selected">Please select</option>
                        <option value="0">Studio</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">5+</option>
                    </select>
                    <div class="error"></div>
                </div>

                <div class="form-group">
                    <label>Price</label>
                    <input type="text" name="price" class="form-control" placeholder="Property's price">
                    <div class="error"></div>
                </div>

                <div class="form-group">
                    <label>Postcode</label>
                    <input type="text" name="postcode" class="form-control" placeholder="Property's postcode">
                    <div class="error"></div>
                </div>

                <div class="form-group">
                    <label>Name</label>
                    <input type="text" name="name" class="form-control"  placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars">
                    <div class="error"></div>
                </div>

                <div class="form-group">
                    <label>Email</label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email">
                    <div class="error"></div>
                </div>

                <div class="form-group">
                    <label>Details</label>
                    <textarea class="form-control" name="description" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Additional details"></textarea>
                    <div class="error"></div>
                </div>

                <div class="text-center"><button type="submit" class="btn btn-theme btn-block btn-md">Send Message</button></div>
            </form>
            <hr class="colorgraph">

        </div>
    </div>
</div>